language: java
dist: xenial
os: linux
jdk:
- openjdk17
cache:
  directories:
  - "$HOME/.m2/repository/"
before_install:
- openssl aes-256-cbc -K $encrypted_352da9e6f448_key -iv $encrypted_352da9e6f448_iv
  -in travis/secrets.tar.enc -out travis/local.secrets.tar -d
- tar xv -C travis -f travis/local.secrets.tar
# modeled off of https://docs.travis-ci.com/user/pull-requests/
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn -Prelease deploy --settings settings.xml; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn -Prelease verify; fi'

env:
  global:
  - secure: mMsRGGivOOeA8iTT1l7MJcx6U/kSnYkZGsFVid0pdMweskrxXbcgiClzPp29LiiOWi5X+zoAYVAFYKxU+Gb3BewQ57hFanjOS97oizqe6oLjuC5qJwlZ/9AXNb+9eaQiXN2AAWecHCO8UhLhNrEPlvfhX7wp5CuyavdmC5J76yTPvghtU3npJMOMCTfCaoMknZJ+tUPzKRPlunwVS2mIo2o8fn8rcMh3hQwrZRdu3lFyHMuuGnMdJ4MtSikjvYsYl0AtYpnlbuV3BIh4ugKlhkMl/fa3y8RS+OuBm8uitCkS1I58fNH3AjXGVHMsD/7YNvGzAHApdp426Ugzl7oZdwn/vnPm+kItMufnsSgK4l6768ab+xjuT01lfdAgqCmLuV9/IHtpUIxiZMkhJ2/3ug1JHuPziKWld4tp1gsWo2/Mc/i8x4SWfagUsDCCmcpiRLw4fOFPU3BRwb2nXsmwkRQxdiJwYso3xPL1q0rorv772XYkCAqwQI7tfNPTQ4pnpgZmaXxgWdiGFSnjfbw+rmURdGZ58Z9a7YEXCPpaVTT4Y/z2jF+12+v7YL1W4XV+5/3fCR2YYegjgyX1vZE0JP5gPIr7dLtDwD/Z64Vshg14VfJYecAlaTLx0peClf8u0M/CWqunv/xbApdEWCCP8TIdyvnVcOdpHC1TqjNkMKU=
  - secure: RJlgx6U1wZjjyajvx0owBNt0ggV2RJTNvPR6OcYCkhdFlOenOB5S3pRkLLNwudK32Y8pCRl+29h7uylsgF3bhHOpi8CTeTM+lSx4wzsfnLQZtt+s7aEXgqK+X5X4BAnrP8k3qsgYczuXOj2zEOGs5IDvdStqz/E4/gDaIeVYf9UAxe/HNzVxGLcvf/QP5TF5LBotQM2G9Nq+y/zuZ+GWgCmxpvbdoljHZPGxo3wei86FecRY125enSQYWUOnK/DTZkl2upq8fGZm6eJpBLZ6997F2Yn1zmiNK92+C35f9XjQMXzI+XJJnMcSkRv0qP9q1LnmrTX6ffBgVXMgxdMQYvu6OZX/jbUGzT8ut/HFW81Aq+r3FuNbiPrUrweeaMdYeAf632OFECqpejgPOMM53+3b3DmSq+sWesAlUbPq+hc7vEen8U/C4wjERz+eqPEdgTNs32pV2NxIKeejDuTZsR78goGPaDCiD3lof4lddg1RQEnAQxcis+0lapSVHaZKAu93CHYmeov/sBJ45iKEGWGPZ38BtROYcKpdfMhuGAF1+IDMH/m+PfpurQghylTRjEEog8cg5BSjlFDkLPi2k2RPMHoxxrwU1ROLyQ3B0lODY9GWvmGCaac6d7CDR4gSkEg/xOE9Zahv4FyW/peLjKpWymQBtKsMExlaKv6ttug=
  - secure: hn/q3il3jCUUZsnH203tjfmjxtsCeQM0OXuobAtaWNV0Emb3Y789BV1ubznuiEz+ZWfgqDwwl6lqC1ksL9XOT6BQGjatmsG1nWpQCzc2DY9WyO6aFi59aAcE3NF+J8hDdQnmX9QmTdUFxQU12Ml8Fb6WXY1+2bw9X/4ZH2p5WGRBKgTpr8Jh6C52zy1nX3QQaXjD4WOQGwDdnHq66K+a0bjidVLs+wE61xhcmV7WEvs59TevzqrU/D7KPUjDqymGCABE7byjkeuwO8dhT1aYFJC1opDXKX6l2BwInKT2rRvbrEO04mRMLrlqa84hRUwUPaCNTEx03rH27HLcFkqP99gB7u/GJWyAtyIrkgJtaX5xt5yrxwjpfzFlmUC5LqUTrXtQCAkAhJdIqRsAXOvPgv/i43H6zi0YNBjB65iJ4A84E01Nvnkrs8SqNOode+6DCJMTYCWjd2bcN5bbPyoGdnnstHFL6MyThs7kXwOPMV5lujPqptWFHw17xCLu9kciU/GcOy1V7jSfZQX3zS25TeSX9Gp3LEJnnCr3gmM9CLdXNqiilNqR5y9JCKfWqflNlk4P1fOrTtt50RRIzRyOiIRiulmpUE4dIHaJFn1m0Akvt1aqXWLHeysLBREkjxMsml5Ja9ma9x+J6mJS+MvnmBm1G+gs7JUR8pVbtmbuSjo=
